@startuml generale
skinparam Linetype ortho
skinparam rectangle {
    borderColor transparent
}
left to right direction
package Biblioteca{
agent App
agent Biblioteca as BibClass
note "DashboardGeneraleView.fxml si trova\nnel package resouces.biblioteca" as N1
agent DashboardGeneraleController
}

rectangle {
package SezioneUtenti{
agent AggiungiUtenteDialog
agent Utente
note "SezioneUtentiView.fxml e AggiungiUtenteDialogView.fxml\nsi trovano nel package resouces.sezioneUtenti" as N2
agent SezioneUtentiController
}

package SezioneLibri{
agent AggiungiLibroDialog
agent Libro
note "SezioneUtentiView.fxml e AggiungiLibroDialogView.fxml\nsi trovano nel package resouces.sezioneLibri" as N3
agent SezioneLibriController
}

package SezionePrestiti{
agent AggiungiPrestitoDialog
agent Prestito
note "SezioneUtentiView.fxml e AggiungiPrestitoDialogView.fxml\nsi trovano nel package resouces.sezionePrestiti" as N4
agent SezionePrestitiController
}
}
Biblioteca <.down. SezioneUtenti
Biblioteca <.down. SezioneLibri
Biblioteca <.down. SezionePrestiti

SezionePrestiti -[hidden]right- SezioneLibri
SezionePrestiti -[hidden]right- SezioneUtenti
SezioneLibri -[hidden]left- SezioneUtenti
@enduml