@startuml act_cancellazione
title Activity Diagram - Cancellazione Utente (UC-6)

|Bibliotecario|
start
|Bibliotecario|
:Seleziona Utente;
:Clicca su "Cancella";

|Sistema|
:Controlla Prestiti Attivi;

if (Prestiti Attivi presenti?) then ([si])
    :Mostra Alert Prestiti Attivi;
    stop
else ([no])
    :Mostra Alert Conferma;
endif

|Bibliotecario|
:Clicca su "OK";

|Sistema|
:Rimuove l'Utente dalla Lista degli Utenti;
:Salva sul File;
:Aggiorna la Tabella;

stop
@enduml